# Generated by Django 3.2.6 on 2021-08-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
    ]
