# Generated by Django 3.2.6 on 2021-08-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_review_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie',
            new_name='book',
        ),
    ]
